### ISSUE TITLE
Adicionar Spring Security 

### ISSUE THREAD

**Issue by hkokt** [hkokt/br.com.agis.api#2]
- [x] Montar autenticação (JWT)
- [x] Apenas o endpoint `/login` será publico ao usuarionão autenticado

**Comment by MDellaCS** [comment]
**Cara vamo usar oq fizemos em BD:**
https://github.com/leorufinx/TodoList-TypeScript-React/tree/main/TodoBackTypeScript/src

**Comment by MDellaCS** [comment]
"_Apenas o endpoint /login será publico ao usuarionão autenticado_"

Acho que já temos isso lá tbm
